### ISSUE TITLE
request to post about info on how to run the bot

### ISSUE THREAD

**Issue by Hazed2004** [reformedmaximus/Ultra-High-Frequency-Arbitrage-Trading-Bot#1]
hey, can you provide me more info about the bot

**Comment by reformedmaximus** [comment]
hey there! what would you like to know exactly ? the main idea of the trading bot is to compare both BTC prices in kucoin and binance at the same time, figure out the delay in price until kucoin catches up to binance and then develop a full proof trading strategy based on that delay with ultra high frequency trade orders that you wouldn't be able to do by hand. I'm currently working on the delay, price & time difference algorithm/logic as it's not as easy as you think to get that data correctly because there are many things that can go wrong and that you need to account for.

**Comment by Hazed2004** [comment]
Hey, I have pretty good experience in programming so if you need any contribution I'm here to help you and I got a doubt, when transferring BTC or any other crypto there will be some transaction fees right which may neutralize the profit or result in loss
Do you have any approach to eliminate this

**Comment by reformedmaximus** [comment]
how can you contribute to the project and have you worked on any arbitrage bots before ? do you have any knowledge about how Kucoin and Binance APIs work ? as for the BTC transfer, that's not something you need to worry about while trading because the trades are happening in one account so you're not transferring BTC from X to Y. the only thing that matters is the trading fee per transaction which I will account for when preparing the trading and order execution strategy. right now I'm tracking the delays as you can see in the arbitrageLog.txt to see how much margin I can play with and so I can base my strategy on it.

**Comment by Hazed2004** [comment]
I have experience in binance and kucoin API s but never worked on arbitrage bots.
I have good understanding in arbitrage strategies so if you need any help lmk

**Comment by reformedmaximus** [comment]
are you able to write code to place high frequency orders ? I need the code to be well documented so I can build upon it : a section for just one order, a section for multi orders at the same time and if you can do some testing that would be perfect, I would need to know the best parameters to ensure speed and profitability ( I'm talking about TimeInForce, STP ) and the push frequency for the HF order placing as it's not mentioned and it's super important to know as a big part of my strategy will be based on it because once an entry point is found the order needs to be place almost instantly. these documentation links should help you if you choose to help : https://www.kucoin.com/docs/beginners/hftrading  https://www.kucoin.com/docs/rest/spot-trading/spot-hf-trade-pro-account/place-hf-order https://www.kucoin.com/docs/rest/spot-trading/spot-hf-trade-pro-account/place-multiple-orders  https://www.kucoin.com/docs/rest/spot-trading/spot-hf-trade-pro-account/place-hf-order-test  https://www.kucoin.com/docs/rest/spot-trading/spot-hf-trade-pro-account/get-active-hf-orders-list
